# Auto-generated card config — 293 cards
# Copy into CARDS_TO_SCRAPE in sales_scraper.py

NEW_CARDS = [

    # ── BASE SET ──
    {
        "card_name": "Alakazam 1/165 Expedition Base Set",
        "search_query": "\"Alakazam\" 1/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Alakazam 1/165 Base Set 2",
        "search_query": "\"Alakazam\" 1/165 \"Base Set 2\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Alakazam 1/165 Base",
        "search_query": "\"Alakazam\" 1/165 \"Base\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Blastoise 2/165 Base Set 2",
        "search_query": "\"Blastoise\" 2/165 \"Base Set 2\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Blastoise 2/165 Base",
        "search_query": "\"Blastoise\" 2/165 \"Base\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Ampharos 2/165 Expedition Base Set",
        "search_query": "\"Ampharos\" 2/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Arbok 3/165 Expedition Base Set",
        "search_query": "\"Arbok\" 3/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Chansey 3/165 Base Set 2",
        "search_query": "\"Chansey\" 3/165 \"Base Set 2\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Chansey 3/165 Base",
        "search_query": "\"Chansey\" 3/165 \"Base\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Charizard 4/165 Base Set 2",
        "search_query": "\"Charizard\" 4/165 \"Base Set 2\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Blastoise 4/165 Expedition Base Set",
        "search_query": "\"Blastoise\" 4/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Charizard 4/165 Base",
        "search_query": "\"Charizard\" 4/165 \"Base\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Clefairy 5/165 Base",
        "search_query": "\"Clefairy\" 5/165 \"Base\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Clefable 5/165 Base Set 2",
        "search_query": "\"Clefable\" 5/165 \"Base Set 2\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Butterfree 5/165 Expedition Base Set",
        "search_query": "\"Butterfree\" 5/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Charizard 6/165 Expedition Base Set",
        "search_query": "\"Charizard\" 6/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Clefairy 6/165 Base Set 2",
        "search_query": "\"Clefairy\" 6/165 \"Base Set 2\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Gyarados 6/165 Base",
        "search_query": "\"Gyarados\" 6/165 \"Base\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Hitmonchan 7/165 Base",
        "search_query": "\"Hitmonchan\" 7/165 \"Base\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Clefable 7/165 Expedition Base Set",
        "search_query": "\"Clefable\" 7/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Gyarados 7/165 Base Set 2",
        "search_query": "\"Gyarados\" 7/165 \"Base Set 2\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Cloyster 8/165 Expedition Base Set",
        "search_query": "\"Cloyster\" 8/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Hitmonchan 8/165 Base Set 2",
        "search_query": "\"Hitmonchan\" 8/165 \"Base Set 2\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Machamp 8/165 Base",
        "search_query": "\"Machamp\" 8/165 \"Base\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Dragonite 9/165 Expedition Base Set",
        "search_query": "\"Dragonite\" 9/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Magneton 9/165 Base",
        "search_query": "\"Magneton\" 9/165 \"Base\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Magneton 9/165 Base Set 2",
        "search_query": "\"Magneton\" 9/165 \"Base Set 2\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Mewtwo 10/165 Base Set 2",
        "search_query": "\"Mewtwo\" 10/165 \"Base Set 2\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Mewtwo 10/165 Base",
        "search_query": "\"Mewtwo\" 10/165 \"Base\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Dugtrio 10/165 Expedition Base Set",
        "search_query": "\"Dugtrio\" 10/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Nidoking 11/165 Base Set 2",
        "search_query": "\"Nidoking\" 11/165 \"Base Set 2\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Fearow 11/165 Expedition Base Set",
        "search_query": "\"Fearow\" 11/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Nidoking 11/165 Base",
        "search_query": "\"Nidoking\" 11/165 \"Base\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Nidoqueen 12/165 Base Set 2",
        "search_query": "\"Nidoqueen\" 12/165 \"Base Set 2\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Feraligatr 12/165 Expedition Base Set",
        "search_query": "\"Feraligatr\" 12/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Ninetales 12/165 Base",
        "search_query": "\"Ninetales\" 12/165 \"Base\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Poliwrath 13/165 Base",
        "search_query": "\"Poliwrath\" 13/165 \"Base\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Gengar 13/165 Expedition Base Set",
        "search_query": "\"Gengar\" 13/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Ninetales 13/165 Base Set 2",
        "search_query": "\"Ninetales\" 13/165 \"Base Set 2\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Raichu 14/165 Base",
        "search_query": "\"Raichu\" 14/165 \"Base\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Golem 14/165 Expedition Base Set",
        "search_query": "\"Golem\" 14/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Pidgeot 14/165 Base Set 2",
        "search_query": "\"Pidgeot\" 14/165 \"Base Set 2\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Poliwrath 15/165 Base Set 2",
        "search_query": "\"Poliwrath\" 15/165 \"Base Set 2\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Venusaur 15/165 Base",
        "search_query": "\"Venusaur\" 15/165 \"Base\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Kingler 15/165 Expedition Base Set",
        "search_query": "\"Kingler\" 15/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Machamp 16/165 Expedition Base Set",
        "search_query": "\"Machamp\" 16/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Raichu 16/165 Base Set 2",
        "search_query": "\"Raichu\" 16/165 \"Base Set 2\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Zapdos 16/165 Base",
        "search_query": "\"Zapdos\" 16/165 \"Base\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Magby 17/165 Expedition Base Set",
        "search_query": "\"Magby\" 17/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Scyther 17/165 Base Set 2",
        "search_query": "\"Scyther\" 17/165 \"Base Set 2\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Meganium 18/165 Expedition Base Set",
        "search_query": "\"Meganium\" 18/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Venusaur 18/165 Base Set 2",
        "search_query": "\"Venusaur\" 18/165 \"Base Set 2\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Mew 19/165 Expedition Base Set",
        "search_query": "\"Mew\" 19/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Wigglytuff 19/165 Base Set 2",
        "search_query": "\"Wigglytuff\" 19/165 \"Base Set 2\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Mewtwo 20/165 Expedition Base Set",
        "search_query": "\"Mewtwo\" 20/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Zapdos 20/165 Base Set 2",
        "search_query": "\"Zapdos\" 20/165 \"Base Set 2\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Ninetales 21/165 Expedition Base Set",
        "search_query": "\"Ninetales\" 21/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Pichu 22/165 Expedition Base Set",
        "search_query": "\"Pichu\" 22/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Pidgeot 23/165 Expedition Base Set",
        "search_query": "\"Pidgeot\" 23/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Poliwrath 24/165 Expedition Base Set",
        "search_query": "\"Poliwrath\" 24/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Raichu 25/165 Expedition Base Set",
        "search_query": "\"Raichu\" 25/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Rapidash 26/165 Expedition Base Set",
        "search_query": "\"Rapidash\" 26/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Skarmory 27/165 Expedition Base Set",
        "search_query": "\"Skarmory\" 27/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Typhlosion 28/165 Expedition Base Set",
        "search_query": "\"Typhlosion\" 28/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Tyranitar 29/165 Expedition Base Set",
        "search_query": "\"Tyranitar\" 29/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Venusaur 30/165 Expedition Base Set",
        "search_query": "\"Venusaur\" 30/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Vileplume 31/165 Expedition Base Set",
        "search_query": "\"Vileplume\" 31/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Weezing 32/165 Expedition Base Set",
        "search_query": "\"Weezing\" 32/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Double Colorless Energy 96/165 Base",
        "search_query": "\"Double Colorless Energy\" 96/165 \"Base\" -lot -bundle -collection -binder",
        "expected_price": 5,
        "min_price": 1.0,
        "category": "base_set",
    },
    {
        "card_name": "Fighting Energy 97/165 Base",
        "search_query": "\"Fighting Energy\" 97/165 \"Base\" -lot -bundle -collection -binder",
        "expected_price": 5,
        "min_price": 1.0,
        "category": "base_set",
    },
    {
        "card_name": "Fire Energy 98/165 Base",
        "search_query": "\"Fire Energy\" 98/165 \"Base\" -lot -bundle -collection -binder",
        "expected_price": 5,
        "min_price": 1.0,
        "category": "base_set",
    },
    {
        "card_name": "Grass Energy 99/165 Base",
        "search_query": "\"Grass Energy\" 99/165 \"Base\" -lot -bundle -collection -binder",
        "expected_price": 5,
        "min_price": 1.0,
        "category": "base_set",
    },
    {
        "card_name": "Lightning Energy 100/165 Base",
        "search_query": "\"Lightning Energy\" 100/165 \"Base\" -lot -bundle -collection -binder",
        "expected_price": 5,
        "min_price": 1.0,
        "category": "base_set",
    },
    {
        "card_name": "Psychic Energy 101/165 Base",
        "search_query": "\"Psychic Energy\" 101/165 \"Base\" -lot -bundle -collection -binder",
        "expected_price": 5,
        "min_price": 1.0,
        "category": "base_set",
    },
    {
        "card_name": "Water Energy 102/165 Base",
        "search_query": "\"Water Energy\" 102/165 \"Base\" -lot -bundle -collection -binder",
        "expected_price": 5,
        "min_price": 1.0,
        "category": "base_set",
    },
    {
        "card_name": "Double Colorless Energy 124/165 Base Set 2",
        "search_query": "\"Double Colorless Energy\" 124/165 \"Base Set 2\" -lot -bundle -collection -binder",
        "expected_price": 5,
        "min_price": 1.0,
        "category": "base_set",
    },
    {
        "card_name": "Fighting Energy 125/165 Base Set 2",
        "search_query": "\"Fighting Energy\" 125/165 \"Base Set 2\" -lot -bundle -collection -binder",
        "expected_price": 5,
        "min_price": 1.0,
        "category": "base_set",
    },
    {
        "card_name": "Fire Energy 126/165 Base Set 2",
        "search_query": "\"Fire Energy\" 126/165 \"Base Set 2\" -lot -bundle -collection -binder",
        "expected_price": 5,
        "min_price": 1.0,
        "category": "base_set",
    },
    {
        "card_name": "Grass Energy 127/165 Base Set 2",
        "search_query": "\"Grass Energy\" 127/165 \"Base Set 2\" -lot -bundle -collection -binder",
        "expected_price": 5,
        "min_price": 1.0,
        "category": "base_set",
    },
    {
        "card_name": "Lightning Energy 128/165 Base Set 2",
        "search_query": "\"Lightning Energy\" 128/165 \"Base Set 2\" -lot -bundle -collection -binder",
        "expected_price": 5,
        "min_price": 1.0,
        "category": "base_set",
    },
    {
        "card_name": "Psychic Energy 129/165 Base Set 2",
        "search_query": "\"Psychic Energy\" 129/165 \"Base Set 2\" -lot -bundle -collection -binder",
        "expected_price": 5,
        "min_price": 1.0,
        "category": "base_set",
    },
    {
        "card_name": "Water Energy 130/165 Base Set 2",
        "search_query": "\"Water Energy\" 130/165 \"Base Set 2\" -lot -bundle -collection -binder",
        "expected_price": 5,
        "min_price": 1.0,
        "category": "base_set",
    },
    {
        "card_name": "Darkness Energy 158/165 Expedition Base Set",
        "search_query": "\"Darkness Energy\" 158/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Metal Energy 159/165 Expedition Base Set",
        "search_query": "\"Metal Energy\" 159/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Fighting Energy 160/165 Expedition Base Set",
        "search_query": "\"Fighting Energy\" 160/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 5,
        "min_price": 1.0,
        "category": "base_set",
    },
    {
        "card_name": "Fire Energy 161/165 Expedition Base Set",
        "search_query": "\"Fire Energy\" 161/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 5,
        "min_price": 1.0,
        "category": "base_set",
    },
    {
        "card_name": "Grass Energy 162/165 Expedition Base Set",
        "search_query": "\"Grass Energy\" 162/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 5,
        "min_price": 1.0,
        "category": "base_set",
    },
    {
        "card_name": "Lightning Energy 163/165 Expedition Base Set",
        "search_query": "\"Lightning Energy\" 163/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 5,
        "min_price": 1.0,
        "category": "base_set",
    },
    {
        "card_name": "Psychic Energy 164/165 Expedition Base Set",
        "search_query": "\"Psychic Energy\" 164/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 5,
        "min_price": 1.0,
        "category": "base_set",
    },
    {
        "card_name": "Water Energy 165/165 Expedition Base Set",
        "search_query": "\"Water Energy\" 165/165 \"Expedition Base Set\" -lot -bundle -collection -binder",
        "expected_price": 5,
        "min_price": 1.0,
        "category": "base_set",
    },

    # ── EVOLVING SKIES ──
    {
        "card_name": "Leafeon VMAX 8/237 Evolving Skies",
        "search_query": "\"Leafeon VMAX\" 8/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Trevenant VMAX 14/237 Evolving Skies",
        "search_query": "\"Trevenant VMAX\" 14/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Flareon VMAX 18/237 Evolving Skies",
        "search_query": "\"Flareon VMAX\" 18/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Gyarados VMAX 29/237 Evolving Skies",
        "search_query": "\"Gyarados VMAX\" 29/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Vaporeon VMAX 30/237 Evolving Skies",
        "search_query": "\"Vaporeon VMAX\" 30/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Glaceon VMAX 41/237 Evolving Skies",
        "search_query": "\"Glaceon VMAX\" 41/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Jolteon VMAX 51/237 Evolving Skies",
        "search_query": "\"Jolteon VMAX\" 51/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Dracozolt VMAX 59/237 Evolving Skies",
        "search_query": "\"Dracozolt VMAX\" 59/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Espeon VMAX 65/237 Evolving Skies",
        "search_query": "\"Espeon VMAX\" 65/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Sylveon VMAX 75/237 Evolving Skies",
        "search_query": "\"Sylveon VMAX\" 75/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Lycanroc VMAX 92/237 Evolving Skies",
        "search_query": "\"Lycanroc VMAX\" 92/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Umbreon VMAX 95/237 Evolving Skies",
        "search_query": "\"Umbreon VMAX\" 95/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Garbodor VMAX 101/237 Evolving Skies",
        "search_query": "\"Garbodor VMAX\" 101/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Rayquaza VMAX 111/237 Evolving Skies",
        "search_query": "\"Rayquaza VMAX\" 111/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Duraludon VMAX 123/237 Evolving Skies",
        "search_query": "\"Duraludon VMAX\" 123/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Leafeon V 166/237 Evolving Skies",
        "search_query": "\"Leafeon V\" 166/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Leafeon V 167/237 Evolving Skies",
        "search_query": "\"Leafeon V\" 167/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Trevenant V 168/237 Evolving Skies",
        "search_query": "\"Trevenant V\" 168/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Flareon V 169/237 Evolving Skies",
        "search_query": "\"Flareon V\" 169/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Volcarona V 170/237 Evolving Skies",
        "search_query": "\"Volcarona V\" 170/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Gyarados V 171/237 Evolving Skies",
        "search_query": "\"Gyarados V\" 171/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Vaporeon V 172/237 Evolving Skies",
        "search_query": "\"Vaporeon V\" 172/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Suicune V 173/237 Evolving Skies",
        "search_query": "\"Suicune V\" 173/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Glaceon V 174/237 Evolving Skies",
        "search_query": "\"Glaceon V\" 174/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Glaceon V 175/237 Evolving Skies",
        "search_query": "\"Glaceon V\" 175/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Arctovish V 176/237 Evolving Skies",
        "search_query": "\"Arctovish V\" 176/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Jolteon V 177/237 Evolving Skies",
        "search_query": "\"Jolteon V\" 177/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Dracozolt V 178/237 Evolving Skies",
        "search_query": "\"Dracozolt V\" 178/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Espeon V 179/237 Evolving Skies",
        "search_query": "\"Espeon V\" 179/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Espeon V 180/237 Evolving Skies",
        "search_query": "\"Espeon V\" 180/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Golurk V 181/237 Evolving Skies",
        "search_query": "\"Golurk V\" 181/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Golurk V 182/237 Evolving Skies",
        "search_query": "\"Golurk V\" 182/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Sylveon V 183/237 Evolving Skies",
        "search_query": "\"Sylveon V\" 183/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Sylveon V 184/237 Evolving Skies",
        "search_query": "\"Sylveon V\" 184/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Medicham V 185/237 Evolving Skies",
        "search_query": "\"Medicham V\" 185/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Medicham V 186/237 Evolving Skies",
        "search_query": "\"Medicham V\" 186/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Lycanroc V 187/237 Evolving Skies",
        "search_query": "\"Lycanroc V\" 187/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Umbreon V 188/237 Evolving Skies",
        "search_query": "\"Umbreon V\" 188/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Umbreon V 189/237 Evolving Skies",
        "search_query": "\"Umbreon V\" 189/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Garbodor V 190/237 Evolving Skies",
        "search_query": "\"Garbodor V\" 190/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Dragonite V 191/237 Evolving Skies",
        "search_query": "\"Dragonite V\" 191/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Dragonite V 192/237 Evolving Skies",
        "search_query": "\"Dragonite V\" 192/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Rayquaza V 193/237 Evolving Skies",
        "search_query": "\"Rayquaza V\" 193/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Rayquaza V 194/237 Evolving Skies",
        "search_query": "\"Rayquaza V\" 194/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Noivern V 195/237 Evolving Skies",
        "search_query": "\"Noivern V\" 195/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Noivern V 196/237 Evolving Skies",
        "search_query": "\"Noivern V\" 196/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Duraludon V 197/237 Evolving Skies",
        "search_query": "\"Duraludon V\" 197/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Duraludon V 198/237 Evolving Skies",
        "search_query": "\"Duraludon V\" 198/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Aroma Lady 199/237 Evolving Skies",
        "search_query": "\"Aroma Lady\" 199/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Copycat 200/237 Evolving Skies",
        "search_query": "\"Copycat\" 200/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Gordie 201/237 Evolving Skies",
        "search_query": "\"Gordie\" 201/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Raihan 202/237 Evolving Skies",
        "search_query": "\"Raihan\" 202/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Zinnia's Resolve 203/237 Evolving Skies",
        "search_query": "\"Zinnia's Resolve\" 203/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Leafeon VMAX 204/237 Evolving Skies",
        "search_query": "\"Leafeon VMAX\" 204/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Leafeon VMAX 205/237 Evolving Skies",
        "search_query": "\"Leafeon VMAX\" 205/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Trevenant VMAX 206/237 Evolving Skies",
        "search_query": "\"Trevenant VMAX\" 206/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Gyarados VMAX 207/237 Evolving Skies",
        "search_query": "\"Gyarados VMAX\" 207/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Glaceon VMAX 208/237 Evolving Skies",
        "search_query": "\"Glaceon VMAX\" 208/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Glaceon VMAX 209/237 Evolving Skies",
        "search_query": "\"Glaceon VMAX\" 209/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Dracozolt VMAX 210/237 Evolving Skies",
        "search_query": "\"Dracozolt VMAX\" 210/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Sylveon VMAX 211/237 Evolving Skies",
        "search_query": "\"Sylveon VMAX\" 211/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Sylveon VMAX 212/237 Evolving Skies",
        "search_query": "\"Sylveon VMAX\" 212/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Lycanroc VMAX 213/237 Evolving Skies",
        "search_query": "\"Lycanroc VMAX\" 213/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Umbreon VMAX 214/237 Evolving Skies",
        "search_query": "\"Umbreon VMAX\" 214/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Umbreon VMAX 215/237 Evolving Skies",
        "search_query": "\"Umbreon VMAX\" 215/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Garbodor VMAX 216/237 Evolving Skies",
        "search_query": "\"Garbodor VMAX\" 216/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Rayquaza VMAX 217/237 Evolving Skies",
        "search_query": "\"Rayquaza VMAX\" 217/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Rayquaza VMAX 218/237 Evolving Skies",
        "search_query": "\"Rayquaza VMAX\" 218/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Duraludon VMAX 219/237 Evolving Skies",
        "search_query": "\"Duraludon VMAX\" 219/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Duraludon VMAX 220/237 Evolving Skies",
        "search_query": "\"Duraludon VMAX\" 220/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Aroma Lady 221/237 Evolving Skies",
        "search_query": "\"Aroma Lady\" 221/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Copycat 222/237 Evolving Skies",
        "search_query": "\"Copycat\" 222/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Gordie 223/237 Evolving Skies",
        "search_query": "\"Gordie\" 223/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Raihan 224/237 Evolving Skies",
        "search_query": "\"Raihan\" 224/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Zinnia's Resolve 225/237 Evolving Skies",
        "search_query": "\"Zinnia's Resolve\" 225/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Froslass 226/237 Evolving Skies",
        "search_query": "\"Froslass\" 226/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Inteleon 227/237 Evolving Skies",
        "search_query": "\"Inteleon\" 227/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Cresselia 228/237 Evolving Skies",
        "search_query": "\"Cresselia\" 228/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Boost Shake 229/237 Evolving Skies",
        "search_query": "\"Boost Shake\" 229/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Crystal Cave 230/237 Evolving Skies",
        "search_query": "\"Crystal Cave\" 230/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Full Face Guard 231/237 Evolving Skies",
        "search_query": "\"Full Face Guard\" 231/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Stormy Mountains 232/237 Evolving Skies",
        "search_query": "\"Stormy Mountains\" 232/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Toy Catcher 233/237 Evolving Skies",
        "search_query": "\"Toy Catcher\" 233/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Turffield Stadium 234/237 Evolving Skies",
        "search_query": "\"Turffield Stadium\" 234/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Lightning Energy 235/237 Evolving Skies",
        "search_query": "\"Lightning Energy\" 235/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Darkness Energy 236/237 Evolving Skies",
        "search_query": "\"Darkness Energy\" 236/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Metal Energy 237/237 Evolving Skies",
        "search_query": "\"Metal Energy\" 237/237 \"Evolving Skies\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },

    # ── SURGING SPARKS ──
    {
        "card_name": "Durant ex 4/252 Surging Sparks",
        "search_query": "\"Durant ex\" 4/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Ceruledge ex 36/252 Surging Sparks",
        "search_query": "\"Ceruledge ex\" 36/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Scovillain ex 37/252 Surging Sparks",
        "search_query": "\"Scovillain ex\" 37/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Milotic ex 42/252 Surging Sparks",
        "search_query": "\"Milotic ex\" 42/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Black Kyurem ex 48/252 Surging Sparks",
        "search_query": "\"Black Kyurem ex\" 48/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Pikachu ex 57/252 Surging Sparks",
        "search_query": "\"Pikachu ex\" 57/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Kilowattrel ex 68/252 Surging Sparks",
        "search_query": "\"Kilowattrel ex\" 68/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Latias ex 76/252 Surging Sparks",
        "search_query": "\"Latias ex\" 76/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Sylveon ex 86/252 Surging Sparks",
        "search_query": "\"Sylveon ex\" 86/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Palossand ex 91/252 Surging Sparks",
        "search_query": "\"Palossand ex\" 91/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Flygon ex 106/252 Surging Sparks",
        "search_query": "\"Flygon ex\" 106/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Hydreigon ex 119/252 Surging Sparks",
        "search_query": "\"Hydreigon ex\" 119/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Archaludon ex 130/252 Surging Sparks",
        "search_query": "\"Archaludon ex\" 130/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Alolan Exeggutor ex 133/252 Surging Sparks",
        "search_query": "\"Alolan Exeggutor ex\" 133/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Tatsugiri ex 142/252 Surging Sparks",
        "search_query": "\"Tatsugiri ex\" 142/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Slaking ex 147/252 Surging Sparks",
        "search_query": "\"Slaking ex\" 147/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Cyclizar ex 159/252 Surging Sparks",
        "search_query": "\"Cyclizar ex\" 159/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Flamigo ex 160/252 Surging Sparks",
        "search_query": "\"Flamigo ex\" 160/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Amulet of Hope 162/252 Surging Sparks",
        "search_query": "\"Amulet of Hope\" 162/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Brilliant Blender 164/252 Surging Sparks",
        "search_query": "\"Brilliant Blender\" 164/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Energy Search Pro 176/252 Surging Sparks",
        "search_query": "\"Energy Search Pro\" 176/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Megaton Blower 182/252 Surging Sparks",
        "search_query": "\"Megaton Blower\" 182/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Miracle Headset 183/252 Surging Sparks",
        "search_query": "\"Miracle Headset\" 183/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Precious Trolley 185/252 Surging Sparks",
        "search_query": "\"Precious Trolley\" 185/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Scramble Switch 186/252 Surging Sparks",
        "search_query": "\"Scramble Switch\" 186/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Enriching Energy 191/252 Surging Sparks",
        "search_query": "\"Enriching Energy\" 191/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Exeggcute 192/252 Surging Sparks",
        "search_query": "\"Exeggcute\" 192/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Vivillon 193/252 Surging Sparks",
        "search_query": "\"Vivillon\" 193/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Shiinotic 194/252 Surging Sparks",
        "search_query": "\"Shiinotic\" 194/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Castform Sunny Form 195/252 Surging Sparks",
        "search_query": "\"Castform Sunny Form\" 195/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Larvesta 196/252 Surging Sparks",
        "search_query": "\"Larvesta\" 196/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Ceruledge 197/252 Surging Sparks",
        "search_query": "\"Ceruledge\" 197/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Feebas 198/252 Surging Sparks",
        "search_query": "\"Feebas\" 198/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Spheal 199/252 Surging Sparks",
        "search_query": "\"Spheal\" 199/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Bruxish 200/252 Surging Sparks",
        "search_query": "\"Bruxish\" 200/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Cetitan 201/252 Surging Sparks",
        "search_query": "\"Cetitan\" 201/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Stunfisk 202/252 Surging Sparks",
        "search_query": "\"Stunfisk\" 202/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Latios 203/252 Surging Sparks",
        "search_query": "\"Latios\" 203/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Mesprit 204/252 Surging Sparks",
        "search_query": "\"Mesprit\" 204/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Phanpy 205/252 Surging Sparks",
        "search_query": "\"Phanpy\" 205/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Vibrava 206/252 Surging Sparks",
        "search_query": "\"Vibrava\" 206/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Clobbopus 207/252 Surging Sparks",
        "search_query": "\"Clobbopus\" 207/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Alolan Dugtrio 208/252 Surging Sparks",
        "search_query": "\"Alolan Dugtrio\" 208/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Skarmory 209/252 Surging Sparks",
        "search_query": "\"Skarmory\" 209/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Flapple 210/252 Surging Sparks",
        "search_query": "\"Flapple\" 210/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Appletun 211/252 Surging Sparks",
        "search_query": "\"Appletun\" 211/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Slakoth 212/252 Surging Sparks",
        "search_query": "\"Slakoth\" 212/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Kecleon 213/252 Surging Sparks",
        "search_query": "\"Kecleon\" 213/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Braviary 214/252 Surging Sparks",
        "search_query": "\"Braviary\" 214/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Durant ex 215/252 Surging Sparks",
        "search_query": "\"Durant ex\" 215/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Scovillain ex 216/252 Surging Sparks",
        "search_query": "\"Scovillain ex\" 216/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Milotic ex 217/252 Surging Sparks",
        "search_query": "\"Milotic ex\" 217/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Black Kyurem ex 218/252 Surging Sparks",
        "search_query": "\"Black Kyurem ex\" 218/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Pikachu ex 219/252 Surging Sparks",
        "search_query": "\"Pikachu ex\" 219/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Latias ex 220/252 Surging Sparks",
        "search_query": "\"Latias ex\" 220/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Palossand ex 221/252 Surging Sparks",
        "search_query": "\"Palossand ex\" 221/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Flygon ex 222/252 Surging Sparks",
        "search_query": "\"Flygon ex\" 222/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Hydreigon ex 223/252 Surging Sparks",
        "search_query": "\"Hydreigon ex\" 223/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Archaludon ex 224/252 Surging Sparks",
        "search_query": "\"Archaludon ex\" 224/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Alolan Exeggutor ex 225/252 Surging Sparks",
        "search_query": "\"Alolan Exeggutor ex\" 225/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Tatsugiri ex 226/252 Surging Sparks",
        "search_query": "\"Tatsugiri ex\" 226/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Slaking ex 227/252 Surging Sparks",
        "search_query": "\"Slaking ex\" 227/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Cyclizar ex 228/252 Surging Sparks",
        "search_query": "\"Cyclizar ex\" 228/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Clemont's Quick Wit 229/252 Surging Sparks",
        "search_query": "\"Clemont's Quick Wit\" 229/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Cyrano 230/252 Surging Sparks",
        "search_query": "\"Cyrano\" 230/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Drasna 231/252 Surging Sparks",
        "search_query": "\"Drasna\" 231/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Drayton 232/252 Surging Sparks",
        "search_query": "\"Drayton\" 232/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Jasmine's Gaze 233/252 Surging Sparks",
        "search_query": "\"Jasmine's Gaze\" 233/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Lisia's Appeal 234/252 Surging Sparks",
        "search_query": "\"Lisia's Appeal\" 234/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Surfer 235/252 Surging Sparks",
        "search_query": "\"Surfer\" 235/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Durant ex 236/252 Surging Sparks",
        "search_query": "\"Durant ex\" 236/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Milotic ex 237/252 Surging Sparks",
        "search_query": "\"Milotic ex\" 237/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Pikachu ex 238/252 Surging Sparks",
        "search_query": "\"Pikachu ex\" 238/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Latias ex 239/252 Surging Sparks",
        "search_query": "\"Latias ex\" 239/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Hydreigon ex 240/252 Surging Sparks",
        "search_query": "\"Hydreigon ex\" 240/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Archaludon ex 241/252 Surging Sparks",
        "search_query": "\"Archaludon ex\" 241/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Alolan Exeggutor ex 242/252 Surging Sparks",
        "search_query": "\"Alolan Exeggutor ex\" 242/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Clemont's Quick Wit 243/252 Surging Sparks",
        "search_query": "\"Clemont's Quick Wit\" 243/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Drayton 244/252 Surging Sparks",
        "search_query": "\"Drayton\" 244/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Jasmine's Gaze 245/252 Surging Sparks",
        "search_query": "\"Jasmine's Gaze\" 245/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Lisia's Appeal 246/252 Surging Sparks",
        "search_query": "\"Lisia's Appeal\" 246/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Pikachu ex 247/252 Surging Sparks",
        "search_query": "\"Pikachu ex\" 247/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Alolan Exeggutor ex 248/252 Surging Sparks",
        "search_query": "\"Alolan Exeggutor ex\" 248/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Counter Gain 249/252 Surging Sparks",
        "search_query": "\"Counter Gain\" 249/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Gravity Mountain 250/252 Surging Sparks",
        "search_query": "\"Gravity Mountain\" 250/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Night Stretcher 251/252 Surging Sparks",
        "search_query": "\"Night Stretcher\" 251/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Jet Energy 252/252 Surging Sparks",
        "search_query": "\"Jet Energy\" 252/252 \"Surging Sparks\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },

    # ── NEO SHINING ──
    {
        "card_name": "Shining Celebi 106/113 Neo Destiny",
        "search_query": "\"Shining Celebi\" 106/113 \"Neo Destiny\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 100.0,
        "category": "neo_shining",
    },
    {
        "card_name": "Shining Charizard 107/113 Neo Destiny",
        "search_query": "\"Shining Charizard\" 107/113 \"Neo Destiny\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 100.0,
        "category": "neo_shining",
    },
    {
        "card_name": "Shining Kabutops 108/113 Neo Destiny",
        "search_query": "\"Shining Kabutops\" 108/113 \"Neo Destiny\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 100.0,
        "category": "neo_shining",
    },
    {
        "card_name": "Shining Mewtwo 109/113 Neo Destiny",
        "search_query": "\"Shining Mewtwo\" 109/113 \"Neo Destiny\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 100.0,
        "category": "neo_shining",
    },
    {
        "card_name": "Shining Noctowl 110/113 Neo Destiny",
        "search_query": "\"Shining Noctowl\" 110/113 \"Neo Destiny\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 100.0,
        "category": "neo_shining",
    },
    {
        "card_name": "Shining Raichu 111/113 Neo Destiny",
        "search_query": "\"Shining Raichu\" 111/113 \"Neo Destiny\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 100.0,
        "category": "neo_shining",
    },
    {
        "card_name": "Shining Steelix 112/113 Neo Destiny",
        "search_query": "\"Shining Steelix\" 112/113 \"Neo Destiny\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 100.0,
        "category": "neo_shining",
    },
    {
        "card_name": "Shining Tyranitar 113/113 Neo Destiny",
        "search_query": "\"Shining Tyranitar\" 113/113 \"Neo Destiny\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 100.0,
        "category": "neo_shining",
    },
    {
        "card_name": "Shining Gyarados 65/66 Neo Revelation",
        "search_query": "\"Shining Gyarados\" 65/66 \"Neo Revelation\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 100.0,
        "category": "neo_shining",
    },
    {
        "card_name": "Shining Magikarp 66/66 Neo Revelation",
        "search_query": "\"Shining Magikarp\" 66/66 \"Neo Revelation\" -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 100.0,
        "category": "neo_shining",
    },

    # ── CRYSTAL CARDS ──
    {
        "card_name": "Crystal Shard 122/122 Skyridge",
        "search_query": "\"Crystal Shard\" 122/122 \"Skyridge\" -lot -bundle -collection -binder",
        "expected_price": 5,
        "min_price": 1,
        "category": "crystal_cards",
    },
    {
        "card_name": "Crystal Energy 146/146 Aquapolis",
        "search_query": "\"Crystal Energy\" 146/146 \"Aquapolis\" -lot -bundle -collection -binder",
        "expected_price": 5,
        "min_price": 1,
        "category": "crystal_cards",
    },

    # ── PHANTASMAL FLAMES ──
    {
        "card_name": "Mega Charizard ex SIR",
        "search_query": "Mega Charizard ex 125 Phantasmal Flames",
        "expected_price": 1000,
        "min_price": 50,
        "category": "phantasmal_flames",
    },
    {
        "card_name": "Mega Blastoise ex SIR",
        "search_query": "Mega Blastoise ex SIR Phantasmal Flames",
        "expected_price": 200,
        "min_price": 20,
        "category": "phantasmal_flames",
    },
    {
        "card_name": "Mega Venusaur ex SIR",
        "search_query": "Mega Venusaur ex SIR Phantasmal Flames",
        "expected_price": 150,
        "min_price": 20,
        "category": "phantasmal_flames",
    },
    {
        "card_name": "Mega Gengar ex SIR",
        "search_query": "Mega Gengar ex SIR Phantasmal Flames",
        "expected_price": 200,
        "min_price": 20,
        "category": "phantasmal_flames",
    },
    {
        "card_name": "Mega Rayquaza ex SIR",
        "search_query": "Mega Rayquaza ex SIR Phantasmal Flames",
        "expected_price": 300,
        "min_price": 20,
        "category": "phantasmal_flames",
    },
    {
        "card_name": "Mega Mewtwo ex SIR",
        "search_query": "Mega Mewtwo ex SIR Phantasmal Flames",
        "expected_price": 250,
        "min_price": 20,
        "category": "phantasmal_flames",
    },
    {
        "card_name": "Mega Gardevoir ex SIR",
        "search_query": "Mega Gardevoir ex SIR Phantasmal Flames",
        "expected_price": 200,
        "min_price": 20,
        "category": "phantasmal_flames",
    },
    {
        "card_name": "Mega Lucario ex SIR",
        "search_query": "Mega Lucario ex SIR Phantasmal Flames",
        "expected_price": 150,
        "min_price": 20,
        "category": "phantasmal_flames",
    },
    {
        "card_name": "Mega Sceptile ex SIR",
        "search_query": "Mega Sceptile ex SIR Phantasmal Flames",
        "expected_price": 100,
        "min_price": 20,
        "category": "phantasmal_flames",
    },
    {
        "card_name": "Mega Swampert ex SIR",
        "search_query": "Mega Swampert ex SIR Phantasmal Flames",
        "expected_price": 100,
        "min_price": 20,
        "category": "phantasmal_flames",
    },
    {
        "card_name": "Mega Blaziken ex SIR",
        "search_query": "Mega Blaziken ex SIR Phantasmal Flames",
        "expected_price": 100,
        "min_price": 20,
        "category": "phantasmal_flames",
    },

    # ── ASCENDED HEROES ──
    {
        "card_name": "Pikachu ex SIR",
        "search_query": "Pikachu ex 276 Ascended Heroes",
        "expected_price": 1500,
        "min_price": 100,
        "category": "ascended_heroes",
    },
    {
        "card_name": "Dragonite ex SIR",
        "search_query": "Dragonite ex SIR Ascended Heroes",
        "expected_price": 200,
        "min_price": 20,
        "category": "ascended_heroes",
    },
    {
        "card_name": "Mewtwo ex SIR",
        "search_query": "Mewtwo ex SIR Ascended Heroes",
        "expected_price": 200,
        "min_price": 20,
        "category": "ascended_heroes",
    },
    {
        "card_name": "Mew ex SIR",
        "search_query": "Mew ex SIR Ascended Heroes",
        "expected_price": 150,
        "min_price": 20,
        "category": "ascended_heroes",
    },
    {
        "card_name": "Gyarados ex SIR",
        "search_query": "Gyarados ex SIR Ascended Heroes",
        "expected_price": 150,
        "min_price": 20,
        "category": "ascended_heroes",
    },
    {
        "card_name": "Arcanine ex SIR",
        "search_query": "Arcanine ex SIR Ascended Heroes",
        "expected_price": 100,
        "min_price": 20,
        "category": "ascended_heroes",
    },
]
