"""
Auto-generated card scraper config
Total cards: 387
"""

# ══════════════════════════════════════════
# Copy everything below into CARDS_TO_SCRAPE
# in sales_scraper.py
# ══════════════════════════════════════════

NEW_CARDS = [

    # ── PRISMATIC EVOLUTIONS ──
    {
        "card_name": "Exeggcute 1/180 Prismatic Evolutions",
        "search_query": "Exeggcute 1 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Exeggutor 2/180 Prismatic Evolutions",
        "search_query": "Exeggutor 2 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Pinsir 3/180 Prismatic Evolutions",
        "search_query": "Pinsir 3 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Budew 4/180 Prismatic Evolutions",
        "search_query": "Budew 4 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Leafeon 5/180 Prismatic Evolutions",
        "search_query": "Leafeon 5 Prismatic Evolutions",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Leafeon ex 6/180 Prismatic Evolutions",
        "search_query": "Leafeon ex 6 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Cottonee 7/180 Prismatic Evolutions",
        "search_query": "Cottonee 7 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Whimsicott 8/180 Prismatic Evolutions",
        "search_query": "Whimsicott 8 Prismatic Evolutions",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Applin 9/180 Prismatic Evolutions",
        "search_query": "Applin 9 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Dipplin 10/180 Prismatic Evolutions",
        "search_query": "Dipplin 10 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Hydrapple ex 11/180 Prismatic Evolutions",
        "search_query": "Hydrapple ex 11 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Teal Mask Ogerpon ex 12/180 Prismatic Evolutions",
        "search_query": "Teal Mask Ogerpon ex 12 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Flareon 13/180 Prismatic Evolutions",
        "search_query": "Flareon 13 Prismatic Evolutions",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Flareon ex 14/180 Prismatic Evolutions",
        "search_query": "Flareon ex 14 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Litleo 15/180 Prismatic Evolutions",
        "search_query": "Litleo 15 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Pyroar 16/180 Prismatic Evolutions",
        "search_query": "Pyroar 16 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Hearthflame Mask Ogerpon ex 17/180 Prismatic Evolutions",
        "search_query": "Hearthflame Mask Ogerpon ex 17 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Slowpoke 18/180 Prismatic Evolutions",
        "search_query": "Slowpoke 18 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Slowking 19/180 Prismatic Evolutions",
        "search_query": "Slowking 19 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Goldeen 20/180 Prismatic Evolutions",
        "search_query": "Goldeen 20 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Seaking 21/180 Prismatic Evolutions",
        "search_query": "Seaking 21 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Vaporeon 22/180 Prismatic Evolutions",
        "search_query": "Vaporeon 22 Prismatic Evolutions",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Vaporeon ex 23/180 Prismatic Evolutions",
        "search_query": "Vaporeon ex 23 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Suicune 24/180 Prismatic Evolutions",
        "search_query": "Suicune 24 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Glaceon 25/180 Prismatic Evolutions",
        "search_query": "Glaceon 25 Prismatic Evolutions",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Glaceon ex 26/180 Prismatic Evolutions",
        "search_query": "Glaceon ex 26 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Wellspring Mask Ogerpon ex 27/180 Prismatic Evolutions",
        "search_query": "Wellspring Mask Ogerpon ex 27 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Pikachu ex 28/180 Prismatic Evolutions",
        "search_query": "Pikachu ex 28 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Jolteon 29/180 Prismatic Evolutions",
        "search_query": "Jolteon 29 Prismatic Evolutions",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Jolteon ex 30/180 Prismatic Evolutions",
        "search_query": "Jolteon ex 30 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Iron Hands ex 31/180 Prismatic Evolutions",
        "search_query": "Iron Hands ex 31 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Iron Thorns ex 32/180 Prismatic Evolutions",
        "search_query": "Iron Thorns ex 32 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Espeon 33/180 Prismatic Evolutions",
        "search_query": "Espeon 33 Prismatic Evolutions",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Espeon ex 34/180 Prismatic Evolutions",
        "search_query": "Espeon ex 34 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Duskull 35/180 Prismatic Evolutions",
        "search_query": "Duskull 35 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Dusclops 36/180 Prismatic Evolutions",
        "search_query": "Dusclops 36 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Dusknoir 37/180 Prismatic Evolutions",
        "search_query": "Dusknoir 37 Prismatic Evolutions",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Spritzee 38/180 Prismatic Evolutions",
        "search_query": "Spritzee 38 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Aromatisse 39/180 Prismatic Evolutions",
        "search_query": "Aromatisse 39 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Sylveon 40/180 Prismatic Evolutions",
        "search_query": "Sylveon 40 Prismatic Evolutions",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Sylveon ex 41/180 Prismatic Evolutions",
        "search_query": "Sylveon ex 41 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Scream Tail 42/180 Prismatic Evolutions",
        "search_query": "Scream Tail 42 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Flutter Mane 43/180 Prismatic Evolutions",
        "search_query": "Flutter Mane 43 Prismatic Evolutions",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Munkidori 44/180 Prismatic Evolutions",
        "search_query": "Munkidori 44 Prismatic Evolutions",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Fezandipiti 45/180 Prismatic Evolutions",
        "search_query": "Fezandipiti 45 Prismatic Evolutions",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Iron Boulder 46/180 Prismatic Evolutions",
        "search_query": "Iron Boulder 46 Prismatic Evolutions",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Larvitar 47/180 Prismatic Evolutions",
        "search_query": "Larvitar 47 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Pupitar 48/180 Prismatic Evolutions",
        "search_query": "Pupitar 48 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Groudon 49/180 Prismatic Evolutions",
        "search_query": "Groudon 49 Prismatic Evolutions",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Riolu 50/180 Prismatic Evolutions",
        "search_query": "Riolu 50 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Lucario ex 51/180 Prismatic Evolutions",
        "search_query": "Lucario ex 51 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Hippopotas 52/180 Prismatic Evolutions",
        "search_query": "Hippopotas 52 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Hippowdon 53/180 Prismatic Evolutions",
        "search_query": "Hippowdon 53 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Bloodmoon Ursaluna 54/180 Prismatic Evolutions",
        "search_query": "Bloodmoon Ursaluna 54 Prismatic Evolutions",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Great Tusk 55/180 Prismatic Evolutions",
        "search_query": "Great Tusk 55 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Sandy Shocks ex 56/180 Prismatic Evolutions",
        "search_query": "Sandy Shocks ex 56 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Okidogi 57/180 Prismatic Evolutions",
        "search_query": "Okidogi 57 Prismatic Evolutions",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Cornerstone Mask Ogerpon ex 58/180 Prismatic Evolutions",
        "search_query": "Cornerstone Mask Ogerpon ex 58 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Umbreon 59/180 Prismatic Evolutions",
        "search_query": "Umbreon 59 Prismatic Evolutions",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Umbreon ex 60/180 Prismatic Evolutions",
        "search_query": "Umbreon ex 60 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Sneasel 61/180 Prismatic Evolutions",
        "search_query": "Sneasel 61 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Houndour 62/180 Prismatic Evolutions",
        "search_query": "Houndour 62 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Houndoom 63/180 Prismatic Evolutions",
        "search_query": "Houndoom 63 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Tyranitar ex 64/180 Prismatic Evolutions",
        "search_query": "Tyranitar ex 64 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Roaring Moon 65/180 Prismatic Evolutions",
        "search_query": "Roaring Moon 65 Prismatic Evolutions",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Bronzor 66/180 Prismatic Evolutions",
        "search_query": "Bronzor 66 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Bronzong 67/180 Prismatic Evolutions",
        "search_query": "Bronzong 67 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Heatran 68/180 Prismatic Evolutions",
        "search_query": "Heatran 68 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Duraludon 69/180 Prismatic Evolutions",
        "search_query": "Duraludon 69 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Archaludon 70/180 Prismatic Evolutions",
        "search_query": "Archaludon 70 Prismatic Evolutions",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Dreepy 71/180 Prismatic Evolutions",
        "search_query": "Dreepy 71 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Drakloak 72/180 Prismatic Evolutions",
        "search_query": "Drakloak 72 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Dragapult ex 73/180 Prismatic Evolutions",
        "search_query": "Dragapult ex 73 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Eevee 74/180 Prismatic Evolutions",
        "search_query": "Eevee 74 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Eevee ex 75/180 Prismatic Evolutions",
        "search_query": "Eevee ex 75 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Snorlax ex 76/180 Prismatic Evolutions",
        "search_query": "Snorlax ex 76 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Hoothoot 77/180 Prismatic Evolutions",
        "search_query": "Hoothoot 77 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Noctowl 78/180 Prismatic Evolutions",
        "search_query": "Noctowl 78 Prismatic Evolutions",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Dunsparce 79/180 Prismatic Evolutions",
        "search_query": "Dunsparce 79 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Dudunsparce 80/180 Prismatic Evolutions",
        "search_query": "Dudunsparce 80 Prismatic Evolutions",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Miltank 81/180 Prismatic Evolutions",
        "search_query": "Miltank 81 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Lugia ex 82/180 Prismatic Evolutions",
        "search_query": "Lugia ex 82 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Buneary 83/180 Prismatic Evolutions",
        "search_query": "Buneary 83 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Lopunny 84/180 Prismatic Evolutions",
        "search_query": "Lopunny 84 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Fan Rotom 85/180 Prismatic Evolutions",
        "search_query": "Fan Rotom 85 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Regigigas 86/180 Prismatic Evolutions",
        "search_query": "Regigigas 86 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Shaymin 87/180 Prismatic Evolutions",
        "search_query": "Shaymin 87 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Furfrou 88/180 Prismatic Evolutions",
        "search_query": "Furfrou 88 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Hawlucha 89/180 Prismatic Evolutions",
        "search_query": "Hawlucha 89 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Noibat 90/180 Prismatic Evolutions",
        "search_query": "Noibat 90 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Noivern ex 91/180 Prismatic Evolutions",
        "search_query": "Noivern ex 91 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Terapagos ex 92/180 Prismatic Evolutions",
        "search_query": "Terapagos ex 92 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Amarys 93/180 Prismatic Evolutions",
        "search_query": "Amarys 93 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Area Zero Underdepths 94/180 Prismatic Evolutions",
        "search_query": "Area Zero Underdepths 94 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Binding Mochi 95/180 Prismatic Evolutions",
        "search_query": "Binding Mochi 95 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Black Belt's Training 96/180 Prismatic Evolutions",
        "search_query": "Black Belt's Training 96 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Black Belt's Training 97/180 Prismatic Evolutions",
        "search_query": "Black Belt's Training 97 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Black Belt's Training 98/180 Prismatic Evolutions",
        "search_query": "Black Belt's Training 98 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Black Belt's Training 99/180 Prismatic Evolutions",
        "search_query": "Black Belt's Training 99 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Briar 100/180 Prismatic Evolutions",
        "search_query": "Briar 100 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Buddy-Buddy Poffin 101/180 Prismatic Evolutions",
        "search_query": "Buddy-Buddy Poffin 101 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Bug Catching Set 102/180 Prismatic Evolutions",
        "search_query": "Bug Catching Set 102 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Carmine 103/180 Prismatic Evolutions",
        "search_query": "Carmine 103 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Ciphermaniac's Codebreaking 104/180 Prismatic Evolutions",
        "search_query": "Ciphermaniac's Codebreaking 104 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Crispin 105/180 Prismatic Evolutions",
        "search_query": "Crispin 105 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Earthen Vessel 106/180 Prismatic Evolutions",
        "search_query": "Earthen Vessel 106 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Explorer's Guidance 107/180 Prismatic Evolutions",
        "search_query": "Explorer's Guidance 107 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Festival Grounds 108/180 Prismatic Evolutions",
        "search_query": "Festival Grounds 108 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Friends in Paldea 109/180 Prismatic Evolutions",
        "search_query": "Friends in Paldea 109 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Glass Trumpet 110/180 Prismatic Evolutions",
        "search_query": "Glass Trumpet 110 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Haban Berry 111/180 Prismatic Evolutions",
        "search_query": "Haban Berry 111 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Janine's Secret Art 112/180 Prismatic Evolutions",
        "search_query": "Janine's Secret Art 112 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Kieran 113/180 Prismatic Evolutions",
        "search_query": "Kieran 113 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Lacey 114/180 Prismatic Evolutions",
        "search_query": "Lacey 114 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Larry's Skill 115/180 Prismatic Evolutions",
        "search_query": "Larry's Skill 115 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Max Rod 116/180 Prismatic Evolutions",
        "search_query": "Max Rod 116 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Maximum Belt 117/180 Prismatic Evolutions",
        "search_query": "Maximum Belt 117 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Ogre's Mask 118/180 Prismatic Evolutions",
        "search_query": "Ogre's Mask 118 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Prime Catcher 119/180 Prismatic Evolutions",
        "search_query": "Prime Catcher 119 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Professor Sada's Vitality 120/180 Prismatic Evolutions",
        "search_query": "Professor Sada's Vitality 120 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Professor Turo's Scenario 121/180 Prismatic Evolutions",
        "search_query": "Professor Turo's Scenario 121 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Professor's Research 122/180 Prismatic Evolutions",
        "search_query": "Professor's Research 122 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Professor's Research 123/180 Prismatic Evolutions",
        "search_query": "Professor's Research 123 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Professor's Research 124/180 Prismatic Evolutions",
        "search_query": "Professor's Research 124 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Professor's Research 125/180 Prismatic Evolutions",
        "search_query": "Professor's Research 125 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Rescue Board 126/180 Prismatic Evolutions",
        "search_query": "Rescue Board 126 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Roto-Stick 127/180 Prismatic Evolutions",
        "search_query": "Roto-Stick 127 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Scoop Up Cyclone 128/180 Prismatic Evolutions",
        "search_query": "Scoop Up Cyclone 128 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Sparkling Crystal 129/180 Prismatic Evolutions",
        "search_query": "Sparkling Crystal 129 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Techno Radar 130/180 Prismatic Evolutions",
        "search_query": "Techno Radar 130 Prismatic Evolutions",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Treasure Tracker 131/180 Prismatic Evolutions",
        "search_query": "Treasure Tracker 131 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Amarys 132/180 Prismatic Evolutions",
        "search_query": "Amarys 132 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Atticus 133/180 Prismatic Evolutions",
        "search_query": "Atticus 133 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Atticus 134/180 Prismatic Evolutions",
        "search_query": "Atticus 134 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Brassius 135/180 Prismatic Evolutions",
        "search_query": "Brassius 135 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Eri 136/180 Prismatic Evolutions",
        "search_query": "Eri 136 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Friends in Paldea 137/180 Prismatic Evolutions",
        "search_query": "Friends in Paldea 137 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Giacomo 138/180 Prismatic Evolutions",
        "search_query": "Giacomo 138 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Larry's Skill 139/180 Prismatic Evolutions",
        "search_query": "Larry's Skill 139 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Mela 140/180 Prismatic Evolutions",
        "search_query": "Mela 140 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Ortega 141/180 Prismatic Evolutions",
        "search_query": "Ortega 141 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Raifort 142/180 Prismatic Evolutions",
        "search_query": "Raifort 142 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Tyme 143/180 Prismatic Evolutions",
        "search_query": "Tyme 143 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Leafeon ex 144/180 Prismatic Evolutions",
        "search_query": "Leafeon ex 144 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Teal Mask Ogerpon ex 145/180 Prismatic Evolutions",
        "search_query": "Teal Mask Ogerpon ex 145 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Flareon ex 146/180 Prismatic Evolutions",
        "search_query": "Flareon ex 146 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Ceruledge ex 147/180 Prismatic Evolutions",
        "search_query": "Ceruledge ex 147 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Hearthflame Mask Ogerpon ex 148/180 Prismatic Evolutions",
        "search_query": "Hearthflame Mask Ogerpon ex 148 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Vaporeon ex 149/180 Prismatic Evolutions",
        "search_query": "Vaporeon ex 149 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Glaceon ex 150/180 Prismatic Evolutions",
        "search_query": "Glaceon ex 150 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Palafin ex 151/180 Prismatic Evolutions",
        "search_query": "Palafin ex 151 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Wellspring Mask Ogerpon ex 152/180 Prismatic Evolutions",
        "search_query": "Wellspring Mask Ogerpon ex 152 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Jolteon ex 153/180 Prismatic Evolutions",
        "search_query": "Jolteon ex 153 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Iron Hands ex 154/180 Prismatic Evolutions",
        "search_query": "Iron Hands ex 154 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Espeon ex 155/180 Prismatic Evolutions",
        "search_query": "Espeon ex 155 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Sylveon ex 156/180 Prismatic Evolutions",
        "search_query": "Sylveon ex 156 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Iron Valiant ex 157/180 Prismatic Evolutions",
        "search_query": "Iron Valiant ex 157 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Iron Crown ex 158/180 Prismatic Evolutions",
        "search_query": "Iron Crown ex 158 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Sandy Shocks ex 159/180 Prismatic Evolutions",
        "search_query": "Sandy Shocks ex 159 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Cornerstone Mask Ogerpon ex 160/180 Prismatic Evolutions",
        "search_query": "Cornerstone Mask Ogerpon ex 160 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Umbreon ex 161/180 Prismatic Evolutions",
        "search_query": "Umbreon ex 161 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Roaring Moon ex 162/180 Prismatic Evolutions",
        "search_query": "Roaring Moon ex 162 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Pecharunt ex 163/180 Prismatic Evolutions",
        "search_query": "Pecharunt ex 163 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Gholdengo ex 164/180 Prismatic Evolutions",
        "search_query": "Gholdengo ex 164 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Dragapult ex 165/180 Prismatic Evolutions",
        "search_query": "Dragapult ex 165 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Raging Bolt ex 166/180 Prismatic Evolutions",
        "search_query": "Raging Bolt ex 166 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Eevee ex 167/180 Prismatic Evolutions",
        "search_query": "Eevee ex 167 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Bloodmoon Ursaluna ex 168/180 Prismatic Evolutions",
        "search_query": "Bloodmoon Ursaluna ex 168 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Terapagos ex 169/180 Prismatic Evolutions",
        "search_query": "Terapagos ex 169 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Amarys 170/180 Prismatic Evolutions",
        "search_query": "Amarys 170 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Crispin 171/180 Prismatic Evolutions",
        "search_query": "Crispin 171 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Drayton 172/180 Prismatic Evolutions",
        "search_query": "Drayton 172 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Janine's Secret Art 173/180 Prismatic Evolutions",
        "search_query": "Janine's Secret Art 173 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Kieran 174/180 Prismatic Evolutions",
        "search_query": "Kieran 174 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Lacey 175/180 Prismatic Evolutions",
        "search_query": "Lacey 175 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Iron Leaves ex 176/180 Prismatic Evolutions",
        "search_query": "Iron Leaves ex 176 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Teal Mask Ogerpon ex 177/180 Prismatic Evolutions",
        "search_query": "Teal Mask Ogerpon ex 177 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Walking Wake ex 178/180 Prismatic Evolutions",
        "search_query": "Walking Wake ex 178 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Pikachu ex 179/180 Prismatic Evolutions",
        "search_query": "Pikachu ex 179 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },
    {
        "card_name": "Terapagos ex 180/180 Prismatic Evolutions",
        "search_query": "Terapagos ex 180 Prismatic Evolutions",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "prismatic_evolutions",
    },

    # ── SV 151 ──
    {
        "card_name": "Bulbasaur 1/207 151",
        "search_query": "Bulbasaur 1 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Ivysaur 2/207 151",
        "search_query": "Ivysaur 2 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Venusaur ex 3/207 151",
        "search_query": "Venusaur ex 3 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Charmander 4/207 151",
        "search_query": "Charmander 4 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Charmeleon 5/207 151",
        "search_query": "Charmeleon 5 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Charizard ex 6/207 151",
        "search_query": "Charizard ex 6 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Squirtle 7/207 151",
        "search_query": "Squirtle 7 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Wartortle 8/207 151",
        "search_query": "Wartortle 8 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Blastoise ex 9/207 151",
        "search_query": "Blastoise ex 9 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Caterpie 10/207 151",
        "search_query": "Caterpie 10 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Metapod 11/207 151",
        "search_query": "Metapod 11 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Butterfree 12/207 151",
        "search_query": "Butterfree 12 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Weedle 13/207 151",
        "search_query": "Weedle 13 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Kakuna 14/207 151",
        "search_query": "Kakuna 14 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Beedrill 15/207 151",
        "search_query": "Beedrill 15 151",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "sv_151",
    },
    {
        "card_name": "Pidgey 16/207 151",
        "search_query": "Pidgey 16 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Pidgeotto 17/207 151",
        "search_query": "Pidgeotto 17 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Pidgeot 18/207 151",
        "search_query": "Pidgeot 18 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Rattata 19/207 151",
        "search_query": "Rattata 19 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Raticate 20/207 151",
        "search_query": "Raticate 20 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Spearow 21/207 151",
        "search_query": "Spearow 21 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Fearow 22/207 151",
        "search_query": "Fearow 22 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Ekans 23/207 151",
        "search_query": "Ekans 23 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Arbok ex 24/207 151",
        "search_query": "Arbok ex 24 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Pikachu 25/207 151",
        "search_query": "Pikachu 25 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Raichu 26/207 151",
        "search_query": "Raichu 26 151",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "sv_151",
    },
    {
        "card_name": "Sandshrew 27/207 151",
        "search_query": "Sandshrew 27 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Sandslash 28/207 151",
        "search_query": "Sandslash 28 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Nidoran \u2640 29/207 151",
        "search_query": "Nidoran \u2640 29 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Nidorina 30/207 151",
        "search_query": "Nidorina 30 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Nidoqueen 31/207 151",
        "search_query": "Nidoqueen 31 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Nidoran \u2642 32/207 151",
        "search_query": "Nidoran \u2642 32 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Nidorino 33/207 151",
        "search_query": "Nidorino 33 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Nidoking 34/207 151",
        "search_query": "Nidoking 34 151",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "sv_151",
    },
    {
        "card_name": "Clefairy 35/207 151",
        "search_query": "Clefairy 35 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Clefable 36/207 151",
        "search_query": "Clefable 36 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Vulpix 37/207 151",
        "search_query": "Vulpix 37 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Ninetales ex 38/207 151",
        "search_query": "Ninetales ex 38 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Jigglypuff 39/207 151",
        "search_query": "Jigglypuff 39 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Wigglytuff ex 40/207 151",
        "search_query": "Wigglytuff ex 40 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Zubat 41/207 151",
        "search_query": "Zubat 41 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Golbat 42/207 151",
        "search_query": "Golbat 42 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Oddish 43/207 151",
        "search_query": "Oddish 43 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Gloom 44/207 151",
        "search_query": "Gloom 44 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Vileplume 45/207 151",
        "search_query": "Vileplume 45 151",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "sv_151",
    },
    {
        "card_name": "Paras 46/207 151",
        "search_query": "Paras 46 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Parasect 47/207 151",
        "search_query": "Parasect 47 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Venonat 48/207 151",
        "search_query": "Venonat 48 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Venomoth 49/207 151",
        "search_query": "Venomoth 49 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Diglett 50/207 151",
        "search_query": "Diglett 50 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Dugtrio 51/207 151",
        "search_query": "Dugtrio 51 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Meowth 52/207 151",
        "search_query": "Meowth 52 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Persian 53/207 151",
        "search_query": "Persian 53 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Psyduck 54/207 151",
        "search_query": "Psyduck 54 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Golduck 55/207 151",
        "search_query": "Golduck 55 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Mankey 56/207 151",
        "search_query": "Mankey 56 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Primeape 57/207 151",
        "search_query": "Primeape 57 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Growlithe 58/207 151",
        "search_query": "Growlithe 58 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Arcanine 59/207 151",
        "search_query": "Arcanine 59 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Poliwag 60/207 151",
        "search_query": "Poliwag 60 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Poliwhirl 61/207 151",
        "search_query": "Poliwhirl 61 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Poliwrath 62/207 151",
        "search_query": "Poliwrath 62 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Abra 63/207 151",
        "search_query": "Abra 63 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Kadabra 64/207 151",
        "search_query": "Kadabra 64 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Alakazam ex 65/207 151",
        "search_query": "Alakazam ex 65 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Machop 66/207 151",
        "search_query": "Machop 66 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Machoke 67/207 151",
        "search_query": "Machoke 67 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Machamp 68/207 151",
        "search_query": "Machamp 68 151",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "sv_151",
    },
    {
        "card_name": "Bellsprout 69/207 151",
        "search_query": "Bellsprout 69 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Weepinbell 70/207 151",
        "search_query": "Weepinbell 70 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Victreebel 71/207 151",
        "search_query": "Victreebel 71 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Tentacool 72/207 151",
        "search_query": "Tentacool 72 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Tentacruel 73/207 151",
        "search_query": "Tentacruel 73 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Geodude 74/207 151",
        "search_query": "Geodude 74 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Graveler 75/207 151",
        "search_query": "Graveler 75 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Golem ex 76/207 151",
        "search_query": "Golem ex 76 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Ponyta 77/207 151",
        "search_query": "Ponyta 77 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Rapidash 78/207 151",
        "search_query": "Rapidash 78 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Slowpoke 79/207 151",
        "search_query": "Slowpoke 79 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Slowbro 80/207 151",
        "search_query": "Slowbro 80 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Magnemite 81/207 151",
        "search_query": "Magnemite 81 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Magneton 82/207 151",
        "search_query": "Magneton 82 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Farfetch'd 83/207 151",
        "search_query": "Farfetch'd 83 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Doduo 84/207 151",
        "search_query": "Doduo 84 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Dodrio 85/207 151",
        "search_query": "Dodrio 85 151",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "sv_151",
    },
    {
        "card_name": "Seel 86/207 151",
        "search_query": "Seel 86 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Dewgong 87/207 151",
        "search_query": "Dewgong 87 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Grimer 88/207 151",
        "search_query": "Grimer 88 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Muk 89/207 151",
        "search_query": "Muk 89 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Shellder 90/207 151",
        "search_query": "Shellder 90 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Cloyster 91/207 151",
        "search_query": "Cloyster 91 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Gastly 92/207 151",
        "search_query": "Gastly 92 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Haunter 93/207 151",
        "search_query": "Haunter 93 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Gengar 94/207 151",
        "search_query": "Gengar 94 151",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "sv_151",
    },
    {
        "card_name": "Onix 95/207 151",
        "search_query": "Onix 95 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Drowzee 96/207 151",
        "search_query": "Drowzee 96 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Hypno 97/207 151",
        "search_query": "Hypno 97 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Krabby 98/207 151",
        "search_query": "Krabby 98 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Kingler 99/207 151",
        "search_query": "Kingler 99 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Voltorb 100/207 151",
        "search_query": "Voltorb 100 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Electrode 101/207 151",
        "search_query": "Electrode 101 151",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "sv_151",
    },
    {
        "card_name": "Exeggcute 102/207 151",
        "search_query": "Exeggcute 102 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Exeggutor 103/207 151",
        "search_query": "Exeggutor 103 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Cubone 104/207 151",
        "search_query": "Cubone 104 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Marowak 105/207 151",
        "search_query": "Marowak 105 151",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "sv_151",
    },
    {
        "card_name": "Hitmonlee 106/207 151",
        "search_query": "Hitmonlee 106 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Hitmonchan 107/207 151",
        "search_query": "Hitmonchan 107 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Lickitung 108/207 151",
        "search_query": "Lickitung 108 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Koffing 109/207 151",
        "search_query": "Koffing 109 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Weezing 110/207 151",
        "search_query": "Weezing 110 151",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "sv_151",
    },
    {
        "card_name": "Rhyhorn 111/207 151",
        "search_query": "Rhyhorn 111 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Rhydon 112/207 151",
        "search_query": "Rhydon 112 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Chansey 113/207 151",
        "search_query": "Chansey 113 151",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "sv_151",
    },
    {
        "card_name": "Tangela 114/207 151",
        "search_query": "Tangela 114 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Kangaskhan ex 115/207 151",
        "search_query": "Kangaskhan ex 115 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Horsea 116/207 151",
        "search_query": "Horsea 116 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Seadra 117/207 151",
        "search_query": "Seadra 117 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Goldeen 118/207 151",
        "search_query": "Goldeen 118 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Seaking 119/207 151",
        "search_query": "Seaking 119 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Staryu 120/207 151",
        "search_query": "Staryu 120 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Starmie 121/207 151",
        "search_query": "Starmie 121 151",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "sv_151",
    },
    {
        "card_name": "Mr. Mime 122/207 151",
        "search_query": "Mr. Mime 122 151",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "sv_151",
    },
    {
        "card_name": "Scyther 123/207 151",
        "search_query": "Scyther 123 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Jynx ex 124/207 151",
        "search_query": "Jynx ex 124 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Electabuzz 125/207 151",
        "search_query": "Electabuzz 125 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Magmar 126/207 151",
        "search_query": "Magmar 126 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Pinsir 127/207 151",
        "search_query": "Pinsir 127 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Tauros 128/207 151",
        "search_query": "Tauros 128 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Magikarp 129/207 151",
        "search_query": "Magikarp 129 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Gyarados 130/207 151",
        "search_query": "Gyarados 130 151",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "sv_151",
    },
    {
        "card_name": "Lapras 131/207 151",
        "search_query": "Lapras 131 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Ditto 132/207 151",
        "search_query": "Ditto 132 151",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "sv_151",
    },
    {
        "card_name": "Eevee 133/207 151",
        "search_query": "Eevee 133 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Vaporeon 134/207 151",
        "search_query": "Vaporeon 134 151",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "sv_151",
    },
    {
        "card_name": "Jolteon 135/207 151",
        "search_query": "Jolteon 135 151",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "sv_151",
    },
    {
        "card_name": "Flareon 136/207 151",
        "search_query": "Flareon 136 151",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "sv_151",
    },
    {
        "card_name": "Porygon 137/207 151",
        "search_query": "Porygon 137 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Omanyte 138/207 151",
        "search_query": "Omanyte 138 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Omastar 139/207 151",
        "search_query": "Omastar 139 151",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "sv_151",
    },
    {
        "card_name": "Kabuto 140/207 151",
        "search_query": "Kabuto 140 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Kabutops 141/207 151",
        "search_query": "Kabutops 141 151",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "sv_151",
    },
    {
        "card_name": "Aerodactyl 142/207 151",
        "search_query": "Aerodactyl 142 151",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "sv_151",
    },
    {
        "card_name": "Snorlax 143/207 151",
        "search_query": "Snorlax 143 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Articuno 144/207 151",
        "search_query": "Articuno 144 151",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "sv_151",
    },
    {
        "card_name": "Zapdos ex 145/207 151",
        "search_query": "Zapdos ex 145 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Moltres 146/207 151",
        "search_query": "Moltres 146 151",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "sv_151",
    },
    {
        "card_name": "Dratini 147/207 151",
        "search_query": "Dratini 147 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Dragonair 148/207 151",
        "search_query": "Dragonair 148 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Dragonite 149/207 151",
        "search_query": "Dragonite 149 151",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "sv_151",
    },
    {
        "card_name": "Mewtwo 150/207 151",
        "search_query": "Mewtwo 150 151",
        "expected_price": 10,
        "min_price": 2.0,
        "category": "sv_151",
    },
    {
        "card_name": "Mew ex 151/207 151",
        "search_query": "Mew ex 151 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Antique Dome Fossil 152/207 151",
        "search_query": "Antique Dome Fossil 152 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Antique Helix Fossil 153/207 151",
        "search_query": "Antique Helix Fossil 153 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Antique Old Amber 154/207 151",
        "search_query": "Antique Old Amber 154 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Big Air Balloon 155/207 151",
        "search_query": "Big Air Balloon 155 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Bill's Transfer 156/207 151",
        "search_query": "Bill's Transfer 156 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Cycling Road 157/207 151",
        "search_query": "Cycling Road 157 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Daisy's Help 158/207 151",
        "search_query": "Daisy's Help 158 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Energy Sticker 159/207 151",
        "search_query": "Energy Sticker 159 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Erika's Invitation 160/207 151",
        "search_query": "Erika's Invitation 160 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Giovanni's Charisma 161/207 151",
        "search_query": "Giovanni's Charisma 161 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Grabber 162/207 151",
        "search_query": "Grabber 162 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Leftovers 163/207 151",
        "search_query": "Leftovers 163 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Protective Goggles 164/207 151",
        "search_query": "Protective Goggles 164 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Rigid Band 165/207 151",
        "search_query": "Rigid Band 165 151",
        "expected_price": 2,
        "min_price": 0.5,
        "category": "sv_151",
    },
    {
        "card_name": "Bulbasaur 166/207 151",
        "search_query": "Bulbasaur 166 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Ivysaur 167/207 151",
        "search_query": "Ivysaur 167 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Charmander 168/207 151",
        "search_query": "Charmander 168 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Charmeleon 169/207 151",
        "search_query": "Charmeleon 169 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Squirtle 170/207 151",
        "search_query": "Squirtle 170 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Wartortle 171/207 151",
        "search_query": "Wartortle 171 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Caterpie 172/207 151",
        "search_query": "Caterpie 172 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Pikachu 173/207 151",
        "search_query": "Pikachu 173 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Nidoking 174/207 151",
        "search_query": "Nidoking 174 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Psyduck 175/207 151",
        "search_query": "Psyduck 175 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Poliwhirl 176/207 151",
        "search_query": "Poliwhirl 176 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Machoke 177/207 151",
        "search_query": "Machoke 177 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Tangela 178/207 151",
        "search_query": "Tangela 178 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Mr. Mime 179/207 151",
        "search_query": "Mr. Mime 179 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Omanyte 180/207 151",
        "search_query": "Omanyte 180 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Dragonair 181/207 151",
        "search_query": "Dragonair 181 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Venusaur ex 182/207 151",
        "search_query": "Venusaur ex 182 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Charizard ex 183/207 151",
        "search_query": "Charizard ex 183 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Blastoise ex 184/207 151",
        "search_query": "Blastoise ex 184 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Arbok ex 185/207 151",
        "search_query": "Arbok ex 185 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Ninetales ex 186/207 151",
        "search_query": "Ninetales ex 186 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Wigglytuff ex 187/207 151",
        "search_query": "Wigglytuff ex 187 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Alakazam ex 188/207 151",
        "search_query": "Alakazam ex 188 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Golem ex 189/207 151",
        "search_query": "Golem ex 189 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Kangaskhan ex 190/207 151",
        "search_query": "Kangaskhan ex 190 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Jynx ex 191/207 151",
        "search_query": "Jynx ex 191 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Zapdos ex 192/207 151",
        "search_query": "Zapdos ex 192 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Mew ex 193/207 151",
        "search_query": "Mew ex 193 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Bill's Transfer 194/207 151",
        "search_query": "Bill's Transfer 194 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Daisy's Help 195/207 151",
        "search_query": "Daisy's Help 195 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Erika's Invitation 196/207 151",
        "search_query": "Erika's Invitation 196 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Giovanni's Charisma 197/207 151",
        "search_query": "Giovanni's Charisma 197 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Venusaur ex 198/207 151",
        "search_query": "Venusaur ex 198 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Charizard ex 199/207 151",
        "search_query": "Charizard ex 199 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Blastoise ex 200/207 151",
        "search_query": "Blastoise ex 200 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Alakazam ex 201/207 151",
        "search_query": "Alakazam ex 201 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Zapdos ex 202/207 151",
        "search_query": "Zapdos ex 202 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Erika's Invitation 203/207 151",
        "search_query": "Erika's Invitation 203 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Giovanni's Charisma 204/207 151",
        "search_query": "Giovanni's Charisma 204 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Mew ex 205/207 151",
        "search_query": "Mew ex 205 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Switch 206/207 151",
        "search_query": "Switch 206 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
    {
        "card_name": "Basic Psychic Energy 207/207 151",
        "search_query": "Basic Psychic Energy 207 151",
        "expected_price": 50,
        "min_price": 20.0,
        "category": "sv_151",
    },
]
