# Auto-generated — 215 cards
# Copy into CARDS_TO_SCRAPE in sales_scraper.py

NEW_CARDS = [

    # ── BASE SET ──
    {
        "card_name": "Alakazam 1/102 Base",
        "search_query": "Alakazam 1 Base -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Blastoise 2/102 Base",
        "search_query": "Blastoise 2 Base -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Chansey 3/102 Base",
        "search_query": "Chansey 3 Base -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Charizard 4/102 Base",
        "search_query": "Charizard 4 Base -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Clefairy 5/102 Base",
        "search_query": "Clefairy 5 Base -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Gyarados 6/102 Base",
        "search_query": "Gyarados 6 Base -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Hitmonchan 7/102 Base",
        "search_query": "Hitmonchan 7 Base -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Machamp 8/102 Base",
        "search_query": "Machamp 8 Base -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Magneton 9/102 Base",
        "search_query": "Magneton 9 Base -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Mewtwo 10/102 Base",
        "search_query": "Mewtwo 10 Base -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Nidoking 11/102 Base",
        "search_query": "Nidoking 11 Base -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Ninetales 12/102 Base",
        "search_query": "Ninetales 12 Base -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Poliwrath 13/102 Base",
        "search_query": "Poliwrath 13 Base -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Raichu 14/102 Base",
        "search_query": "Raichu 14 Base -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Venusaur 15/102 Base",
        "search_query": "Venusaur 15 Base -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },
    {
        "card_name": "Zapdos 16/102 Base",
        "search_query": "Zapdos 16 Base -lot -bundle -collection -binder",
        "expected_price": 20,
        "min_price": 5.0,
        "category": "base_set",
    },

    # ── EVOLVING SKIES ──
    {
        "card_name": "Leafeon VMAX 8/203 Evolving Skies",
        "search_query": "Leafeon VMAX 8 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Trevenant VMAX 14/203 Evolving Skies",
        "search_query": "Trevenant VMAX 14 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Flareon VMAX 18/203 Evolving Skies",
        "search_query": "Flareon VMAX 18 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Gyarados VMAX 29/203 Evolving Skies",
        "search_query": "Gyarados VMAX 29 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Vaporeon VMAX 30/203 Evolving Skies",
        "search_query": "Vaporeon VMAX 30 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Glaceon VMAX 41/203 Evolving Skies",
        "search_query": "Glaceon VMAX 41 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Jolteon VMAX 51/203 Evolving Skies",
        "search_query": "Jolteon VMAX 51 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Dracozolt VMAX 59/203 Evolving Skies",
        "search_query": "Dracozolt VMAX 59 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Espeon VMAX 65/203 Evolving Skies",
        "search_query": "Espeon VMAX 65 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Sylveon VMAX 75/203 Evolving Skies",
        "search_query": "Sylveon VMAX 75 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Lycanroc VMAX 92/203 Evolving Skies",
        "search_query": "Lycanroc VMAX 92 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Umbreon VMAX 95/203 Evolving Skies",
        "search_query": "Umbreon VMAX 95 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Garbodor VMAX 101/203 Evolving Skies",
        "search_query": "Garbodor VMAX 101 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Rayquaza VMAX 111/203 Evolving Skies",
        "search_query": "Rayquaza VMAX 111 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Duraludon VMAX 123/203 Evolving Skies",
        "search_query": "Duraludon VMAX 123 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Leafeon V 166/203 Evolving Skies",
        "search_query": "Leafeon V 166 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Leafeon V 167/203 Evolving Skies",
        "search_query": "Leafeon V 167 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Trevenant V 168/203 Evolving Skies",
        "search_query": "Trevenant V 168 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Flareon V 169/203 Evolving Skies",
        "search_query": "Flareon V 169 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Volcarona V 170/203 Evolving Skies",
        "search_query": "Volcarona V 170 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Gyarados V 171/203 Evolving Skies",
        "search_query": "Gyarados V 171 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Vaporeon V 172/203 Evolving Skies",
        "search_query": "Vaporeon V 172 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Suicune V 173/203 Evolving Skies",
        "search_query": "Suicune V 173 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Glaceon V 174/203 Evolving Skies",
        "search_query": "Glaceon V 174 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Glaceon V 175/203 Evolving Skies",
        "search_query": "Glaceon V 175 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Arctovish V 176/203 Evolving Skies",
        "search_query": "Arctovish V 176 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Jolteon V 177/203 Evolving Skies",
        "search_query": "Jolteon V 177 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Dracozolt V 178/203 Evolving Skies",
        "search_query": "Dracozolt V 178 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Espeon V 179/203 Evolving Skies",
        "search_query": "Espeon V 179 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Espeon V 180/203 Evolving Skies",
        "search_query": "Espeon V 180 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Golurk V 181/203 Evolving Skies",
        "search_query": "Golurk V 181 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Golurk V 182/203 Evolving Skies",
        "search_query": "Golurk V 182 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Sylveon V 183/203 Evolving Skies",
        "search_query": "Sylveon V 183 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Sylveon V 184/203 Evolving Skies",
        "search_query": "Sylveon V 184 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Medicham V 185/203 Evolving Skies",
        "search_query": "Medicham V 185 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Medicham V 186/203 Evolving Skies",
        "search_query": "Medicham V 186 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Lycanroc V 187/203 Evolving Skies",
        "search_query": "Lycanroc V 187 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Umbreon V 188/203 Evolving Skies",
        "search_query": "Umbreon V 188 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Umbreon V 189/203 Evolving Skies",
        "search_query": "Umbreon V 189 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Garbodor V 190/203 Evolving Skies",
        "search_query": "Garbodor V 190 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Dragonite V 191/203 Evolving Skies",
        "search_query": "Dragonite V 191 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Dragonite V 192/203 Evolving Skies",
        "search_query": "Dragonite V 192 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Rayquaza V 193/203 Evolving Skies",
        "search_query": "Rayquaza V 193 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Rayquaza V 194/203 Evolving Skies",
        "search_query": "Rayquaza V 194 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Noivern V 195/203 Evolving Skies",
        "search_query": "Noivern V 195 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Noivern V 196/203 Evolving Skies",
        "search_query": "Noivern V 196 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Duraludon V 197/203 Evolving Skies",
        "search_query": "Duraludon V 197 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Duraludon V 198/203 Evolving Skies",
        "search_query": "Duraludon V 198 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Aroma Lady 199/203 Evolving Skies",
        "search_query": "Aroma Lady 199 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Copycat 200/203 Evolving Skies",
        "search_query": "Copycat 200 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Gordie 201/203 Evolving Skies",
        "search_query": "Gordie 201 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Raihan 202/203 Evolving Skies",
        "search_query": "Raihan 202 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Zinnia's Resolve 203/203 Evolving Skies",
        "search_query": "Zinnia's Resolve 203 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Leafeon VMAX 204/203 Evolving Skies",
        "search_query": "Leafeon VMAX 204 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Leafeon VMAX 205/203 Evolving Skies",
        "search_query": "Leafeon VMAX 205 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Trevenant VMAX 206/203 Evolving Skies",
        "search_query": "Trevenant VMAX 206 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Gyarados VMAX 207/203 Evolving Skies",
        "search_query": "Gyarados VMAX 207 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Glaceon VMAX 208/203 Evolving Skies",
        "search_query": "Glaceon VMAX 208 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Glaceon VMAX 209/203 Evolving Skies",
        "search_query": "Glaceon VMAX 209 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Dracozolt VMAX 210/203 Evolving Skies",
        "search_query": "Dracozolt VMAX 210 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Sylveon VMAX 211/203 Evolving Skies",
        "search_query": "Sylveon VMAX 211 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Sylveon VMAX 212/203 Evolving Skies",
        "search_query": "Sylveon VMAX 212 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Lycanroc VMAX 213/203 Evolving Skies",
        "search_query": "Lycanroc VMAX 213 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Umbreon VMAX 214/203 Evolving Skies",
        "search_query": "Umbreon VMAX 214 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Umbreon VMAX 215/203 Evolving Skies",
        "search_query": "Umbreon VMAX 215 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Garbodor VMAX 216/203 Evolving Skies",
        "search_query": "Garbodor VMAX 216 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Rayquaza VMAX 217/203 Evolving Skies",
        "search_query": "Rayquaza VMAX 217 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Rayquaza VMAX 218/203 Evolving Skies",
        "search_query": "Rayquaza VMAX 218 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Duraludon VMAX 219/203 Evolving Skies",
        "search_query": "Duraludon VMAX 219 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Duraludon VMAX 220/203 Evolving Skies",
        "search_query": "Duraludon VMAX 220 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Aroma Lady 221/203 Evolving Skies",
        "search_query": "Aroma Lady 221 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Copycat 222/203 Evolving Skies",
        "search_query": "Copycat 222 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Gordie 223/203 Evolving Skies",
        "search_query": "Gordie 223 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Raihan 224/203 Evolving Skies",
        "search_query": "Raihan 224 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Zinnia's Resolve 225/203 Evolving Skies",
        "search_query": "Zinnia's Resolve 225 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Froslass 226/203 Evolving Skies",
        "search_query": "Froslass 226 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Inteleon 227/203 Evolving Skies",
        "search_query": "Inteleon 227 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Cresselia 228/203 Evolving Skies",
        "search_query": "Cresselia 228 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Boost Shake 229/203 Evolving Skies",
        "search_query": "Boost Shake 229 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Crystal Cave 230/203 Evolving Skies",
        "search_query": "Crystal Cave 230 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Full Face Guard 231/203 Evolving Skies",
        "search_query": "Full Face Guard 231 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Stormy Mountains 232/203 Evolving Skies",
        "search_query": "Stormy Mountains 232 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Toy Catcher 233/203 Evolving Skies",
        "search_query": "Toy Catcher 233 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Turffield Stadium 234/203 Evolving Skies",
        "search_query": "Turffield Stadium 234 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Lightning Energy 235/203 Evolving Skies",
        "search_query": "Lightning Energy 235 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Darkness Energy 236/203 Evolving Skies",
        "search_query": "Darkness Energy 236 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },
    {
        "card_name": "Metal Energy 237/203 Evolving Skies",
        "search_query": "Metal Energy 237 Evolving Skies -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 20.0,
        "category": "evolving_skies",
    },

    # ── SURGING SPARKS ──
    {
        "card_name": "Durant ex 4/191 Surging Sparks",
        "search_query": "Durant ex 4 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Ceruledge ex 36/191 Surging Sparks",
        "search_query": "Ceruledge ex 36 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Scovillain ex 37/191 Surging Sparks",
        "search_query": "Scovillain ex 37 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Milotic ex 42/191 Surging Sparks",
        "search_query": "Milotic ex 42 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Black Kyurem ex 48/191 Surging Sparks",
        "search_query": "Black Kyurem ex 48 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Pikachu ex 57/191 Surging Sparks",
        "search_query": "Pikachu ex 57 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Kilowattrel ex 68/191 Surging Sparks",
        "search_query": "Kilowattrel ex 68 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Latias ex 76/191 Surging Sparks",
        "search_query": "Latias ex 76 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Sylveon ex 86/191 Surging Sparks",
        "search_query": "Sylveon ex 86 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Palossand ex 91/191 Surging Sparks",
        "search_query": "Palossand ex 91 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Flygon ex 106/191 Surging Sparks",
        "search_query": "Flygon ex 106 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Hydreigon ex 119/191 Surging Sparks",
        "search_query": "Hydreigon ex 119 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Archaludon ex 130/191 Surging Sparks",
        "search_query": "Archaludon ex 130 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Alolan Exeggutor ex 133/191 Surging Sparks",
        "search_query": "Alolan Exeggutor ex 133 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Tatsugiri ex 142/191 Surging Sparks",
        "search_query": "Tatsugiri ex 142 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Slaking ex 147/191 Surging Sparks",
        "search_query": "Slaking ex 147 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Cyclizar ex 159/191 Surging Sparks",
        "search_query": "Cyclizar ex 159 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Flamigo ex 160/191 Surging Sparks",
        "search_query": "Flamigo ex 160 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Amulet of Hope 162/191 Surging Sparks",
        "search_query": "Amulet of Hope 162 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Brilliant Blender 164/191 Surging Sparks",
        "search_query": "Brilliant Blender 164 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Energy Search Pro 176/191 Surging Sparks",
        "search_query": "Energy Search Pro 176 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Megaton Blower 182/191 Surging Sparks",
        "search_query": "Megaton Blower 182 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Miracle Headset 183/191 Surging Sparks",
        "search_query": "Miracle Headset 183 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Precious Trolley 185/191 Surging Sparks",
        "search_query": "Precious Trolley 185 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Scramble Switch 186/191 Surging Sparks",
        "search_query": "Scramble Switch 186 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Enriching Energy 191/191 Surging Sparks",
        "search_query": "Enriching Energy 191 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Exeggcute 192/191 Surging Sparks",
        "search_query": "Exeggcute 192 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Vivillon 193/191 Surging Sparks",
        "search_query": "Vivillon 193 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Shiinotic 194/191 Surging Sparks",
        "search_query": "Shiinotic 194 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Castform Sunny Form 195/191 Surging Sparks",
        "search_query": "Castform Sunny Form 195 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Larvesta 196/191 Surging Sparks",
        "search_query": "Larvesta 196 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Ceruledge 197/191 Surging Sparks",
        "search_query": "Ceruledge 197 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Feebas 198/191 Surging Sparks",
        "search_query": "Feebas 198 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Spheal 199/191 Surging Sparks",
        "search_query": "Spheal 199 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Bruxish 200/191 Surging Sparks",
        "search_query": "Bruxish 200 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Cetitan 201/191 Surging Sparks",
        "search_query": "Cetitan 201 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Stunfisk 202/191 Surging Sparks",
        "search_query": "Stunfisk 202 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Latios 203/191 Surging Sparks",
        "search_query": "Latios 203 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Mesprit 204/191 Surging Sparks",
        "search_query": "Mesprit 204 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Phanpy 205/191 Surging Sparks",
        "search_query": "Phanpy 205 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Vibrava 206/191 Surging Sparks",
        "search_query": "Vibrava 206 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Clobbopus 207/191 Surging Sparks",
        "search_query": "Clobbopus 207 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Alolan Dugtrio 208/191 Surging Sparks",
        "search_query": "Alolan Dugtrio 208 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Skarmory 209/191 Surging Sparks",
        "search_query": "Skarmory 209 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Flapple 210/191 Surging Sparks",
        "search_query": "Flapple 210 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Appletun 211/191 Surging Sparks",
        "search_query": "Appletun 211 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Slakoth 212/191 Surging Sparks",
        "search_query": "Slakoth 212 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Kecleon 213/191 Surging Sparks",
        "search_query": "Kecleon 213 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Braviary 214/191 Surging Sparks",
        "search_query": "Braviary 214 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Durant ex 215/191 Surging Sparks",
        "search_query": "Durant ex 215 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Scovillain ex 216/191 Surging Sparks",
        "search_query": "Scovillain ex 216 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Milotic ex 217/191 Surging Sparks",
        "search_query": "Milotic ex 217 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Black Kyurem ex 218/191 Surging Sparks",
        "search_query": "Black Kyurem ex 218 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Pikachu ex 219/191 Surging Sparks",
        "search_query": "Pikachu ex 219 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Latias ex 220/191 Surging Sparks",
        "search_query": "Latias ex 220 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Palossand ex 221/191 Surging Sparks",
        "search_query": "Palossand ex 221 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Flygon ex 222/191 Surging Sparks",
        "search_query": "Flygon ex 222 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Hydreigon ex 223/191 Surging Sparks",
        "search_query": "Hydreigon ex 223 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Archaludon ex 224/191 Surging Sparks",
        "search_query": "Archaludon ex 224 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Alolan Exeggutor ex 225/191 Surging Sparks",
        "search_query": "Alolan Exeggutor ex 225 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Tatsugiri ex 226/191 Surging Sparks",
        "search_query": "Tatsugiri ex 226 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Slaking ex 227/191 Surging Sparks",
        "search_query": "Slaking ex 227 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Cyclizar ex 228/191 Surging Sparks",
        "search_query": "Cyclizar ex 228 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Clemont's Quick Wit 229/191 Surging Sparks",
        "search_query": "Clemont's Quick Wit 229 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Cyrano 230/191 Surging Sparks",
        "search_query": "Cyrano 230 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Drasna 231/191 Surging Sparks",
        "search_query": "Drasna 231 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Drayton 232/191 Surging Sparks",
        "search_query": "Drayton 232 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Jasmine's Gaze 233/191 Surging Sparks",
        "search_query": "Jasmine's Gaze 233 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Lisia's Appeal 234/191 Surging Sparks",
        "search_query": "Lisia's Appeal 234 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Surfer 235/191 Surging Sparks",
        "search_query": "Surfer 235 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Durant ex 236/191 Surging Sparks",
        "search_query": "Durant ex 236 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Milotic ex 237/191 Surging Sparks",
        "search_query": "Milotic ex 237 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Pikachu ex 238/191 Surging Sparks",
        "search_query": "Pikachu ex 238 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Latias ex 239/191 Surging Sparks",
        "search_query": "Latias ex 239 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Hydreigon ex 240/191 Surging Sparks",
        "search_query": "Hydreigon ex 240 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Archaludon ex 241/191 Surging Sparks",
        "search_query": "Archaludon ex 241 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Alolan Exeggutor ex 242/191 Surging Sparks",
        "search_query": "Alolan Exeggutor ex 242 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Clemont's Quick Wit 243/191 Surging Sparks",
        "search_query": "Clemont's Quick Wit 243 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Drayton 244/191 Surging Sparks",
        "search_query": "Drayton 244 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Jasmine's Gaze 245/191 Surging Sparks",
        "search_query": "Jasmine's Gaze 245 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Lisia's Appeal 246/191 Surging Sparks",
        "search_query": "Lisia's Appeal 246 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Pikachu ex 247/191 Surging Sparks",
        "search_query": "Pikachu ex 247 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Alolan Exeggutor ex 248/191 Surging Sparks",
        "search_query": "Alolan Exeggutor ex 248 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Counter Gain 249/191 Surging Sparks",
        "search_query": "Counter Gain 249 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Gravity Mountain 250/191 Surging Sparks",
        "search_query": "Gravity Mountain 250 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Night Stretcher 251/191 Surging Sparks",
        "search_query": "Night Stretcher 251 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },
    {
        "card_name": "Jet Energy 252/191 Surging Sparks",
        "search_query": "Jet Energy 252 Surging Sparks -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 10.0,
        "category": "surging_sparks",
    },

    # ── NEO SHINING ──
    {
        "card_name": "Shining Celebi 106/105 Neo Destiny",
        "search_query": "Shining Celebi 106 Neo Destiny -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 100.0,
        "category": "neo_shining",
    },
    {
        "card_name": "Shining Charizard 107/105 Neo Destiny",
        "search_query": "Shining Charizard 107 Neo Destiny -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 100.0,
        "category": "neo_shining",
    },
    {
        "card_name": "Shining Kabutops 108/105 Neo Destiny",
        "search_query": "Shining Kabutops 108 Neo Destiny -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 100.0,
        "category": "neo_shining",
    },
    {
        "card_name": "Shining Mewtwo 109/105 Neo Destiny",
        "search_query": "Shining Mewtwo 109 Neo Destiny -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 100.0,
        "category": "neo_shining",
    },
    {
        "card_name": "Shining Noctowl 110/105 Neo Destiny",
        "search_query": "Shining Noctowl 110 Neo Destiny -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 100.0,
        "category": "neo_shining",
    },
    {
        "card_name": "Shining Raichu 111/105 Neo Destiny",
        "search_query": "Shining Raichu 111 Neo Destiny -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 100.0,
        "category": "neo_shining",
    },
    {
        "card_name": "Shining Steelix 112/105 Neo Destiny",
        "search_query": "Shining Steelix 112 Neo Destiny -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 100.0,
        "category": "neo_shining",
    },
    {
        "card_name": "Shining Tyranitar 113/105 Neo Destiny",
        "search_query": "Shining Tyranitar 113 Neo Destiny -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 100.0,
        "category": "neo_shining",
    },
    {
        "card_name": "Shining Gyarados 65/64 Neo Revelation",
        "search_query": "Shining Gyarados 65 Neo Revelation -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 100.0,
        "category": "neo_shining",
    },
    {
        "card_name": "Shining Magikarp 66/64 Neo Revelation",
        "search_query": "Shining Magikarp 66 Neo Revelation -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 100.0,
        "category": "neo_shining",
    },

    # ── CRYSTAL CARDS ──
    {
        "card_name": "Crystal Shard 122/144 Skyridge",
        "search_query": "Crystal Shard 122 Skyridge -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 200.0,
        "category": "crystal_cards",
    },
    {
        "card_name": "Crystal Energy 146/147 Aquapolis",
        "search_query": "Crystal Energy 146 Aquapolis -lot -bundle -collection -binder",
        "expected_price": 100,
        "min_price": 200.0,
        "category": "crystal_cards",
    },

    # ── PHANTASMAL FLAMES ──
    {
        "card_name": "Mega Charizard ex SIR Phantasmal Flames",
        "search_query": "Mega Charizard ex SIR 125 Phantasmal Flames",
        "expected_price": 1000,
        "min_price": 50,
        "category": "phantasmal_flames",
    },
    {
        "card_name": "Mega Blastoise ex SIR Phantasmal Flames",
        "search_query": "Mega Blastoise ex SIR Phantasmal Flames",
        "expected_price": 200,
        "min_price": 20,
        "category": "phantasmal_flames",
    },
    {
        "card_name": "Mega Venusaur ex SIR Phantasmal Flames",
        "search_query": "Mega Venusaur ex SIR Phantasmal Flames",
        "expected_price": 150,
        "min_price": 20,
        "category": "phantasmal_flames",
    },
    {
        "card_name": "Mega Gengar ex SIR Phantasmal Flames",
        "search_query": "Mega Gengar ex SIR Phantasmal Flames",
        "expected_price": 200,
        "min_price": 20,
        "category": "phantasmal_flames",
    },
    {
        "card_name": "Mega Rayquaza ex SIR Phantasmal Flames",
        "search_query": "Mega Rayquaza ex SIR Phantasmal Flames",
        "expected_price": 300,
        "min_price": 20,
        "category": "phantasmal_flames",
    },
    {
        "card_name": "Mega Mewtwo ex SIR Phantasmal Flames",
        "search_query": "Mega Mewtwo ex SIR Phantasmal Flames",
        "expected_price": 250,
        "min_price": 20,
        "category": "phantasmal_flames",
    },
    {
        "card_name": "Mega Gardevoir ex SIR Phantasmal Flames",
        "search_query": "Mega Gardevoir ex SIR Phantasmal Flames",
        "expected_price": 200,
        "min_price": 20,
        "category": "phantasmal_flames",
    },
    {
        "card_name": "Mega Lucario ex SIR Phantasmal Flames",
        "search_query": "Mega Lucario ex SIR Phantasmal Flames",
        "expected_price": 150,
        "min_price": 20,
        "category": "phantasmal_flames",
    },

    # ── ASCENDED HEROES ──
    {
        "card_name": "Pikachu ex SIR Ascended Heroes",
        "search_query": "Pikachu ex 276 SIR Ascended Heroes",
        "expected_price": 1500,
        "min_price": 100,
        "category": "ascended_heroes",
    },
    {
        "card_name": "Dragonite ex SIR Ascended Heroes",
        "search_query": "Dragonite ex SIR Ascended Heroes",
        "expected_price": 200,
        "min_price": 20,
        "category": "ascended_heroes",
    },
    {
        "card_name": "Mewtwo ex SIR Ascended Heroes",
        "search_query": "Mewtwo ex SIR Ascended Heroes",
        "expected_price": 200,
        "min_price": 20,
        "category": "ascended_heroes",
    },
    {
        "card_name": "Mew ex SIR Ascended Heroes",
        "search_query": "Mew ex SIR Ascended Heroes",
        "expected_price": 150,
        "min_price": 20,
        "category": "ascended_heroes",
    },
    {
        "card_name": "Gyarados ex SIR Ascended Heroes",
        "search_query": "Gyarados ex SIR Ascended Heroes",
        "expected_price": 150,
        "min_price": 20,
        "category": "ascended_heroes",
    },
]
